### ISSUE TITLE
Mouse event lag

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/datamapper-ui#35] opened 2017-04-10 13:30 UTC
Seems like at least when running in the context of the ipaas console, there's a lag when you click on data mapper fields, i.e. you click the left and right column and the line doesn't show up until you click again in one of the columns, then the line is drawn connecting the previously selected fields.  I'll see if I can upload a gif/video that shows the problem.

**Comment by mattrpav** [comment] 2017-04-10 17:42
@gashcrumb we originally had a line-that-follows-the-mouse effect enabled and we disabled it temporarily while we were finalizing styling and preparing for drag 'n drop feature coding.

Is the line-that-follows-the-mouse effect demo critical?

**Comment by gashcrumb** [comment] 2017-04-10 17:58
It's different from that, here, let me see if I can get a screen capture of it in action...

**Comment by gashcrumb** [comment] 2017-04-10 18:14
Hopefully you can make out where the mouse clicks happen in this one...  If you can tell it feels like the action on each mouse event is delayed by one, i.e. I click on a field, the *last* field I had clicked on highlights, etc.

![ezgif-3-f01b6cd404](https://cloud.githubusercontent.com/assets/351660/24875959/e482865a-1df7-11e7-8806-5cf36bb9ea09.gif)

**Comment by jbakermd** [comment] 2017-04-11 16:44
The first issue I noticed in reproducing this was there was an exception trying to save the mapping data. That issue was due to a stale mapping from a previous version of the inspection service. It referred to fields with a lowercase name such as "User.name" before, but now it refers to them as "User.Name". 

When serializing for saving, the previous (stale) mapping referred to "User.name" - which was a field that did not exist. Our UI exception handling code did not anticipate this sort of issue, and simply exploded. This has been changed to log an error about the missing field, drop the mapping for that particular field, and continue gracefully.

An example graceful logged message is like so:

Caught exception while attempting to serialize mapping, skipping.  

With data logged including details about which field was missing, and relevant mapping configuration.

This will be fixed in the next commit.

**Comment by jbakermd** [comment] 2017-04-11 16:44
The issue of mouse event lag is still happening despite the above fix, so I'm looking into that currently.

**Comment by jbakermd** [comment] 2017-04-11 17:01
In debugging this issue I've noticed the host component for the data mapper has an out of date initialization sequence - should I log those details as an issue on the data mapper ui or over in the ipaas ui project? @gashcrumb - thoughts?

**Comment by gashcrumb** [comment] 2017-04-11 17:03
@jbakermd absolutely, you can either just add the details here or you can create an issue and assign it to me -> https://github.com/redhat-ipaas/ipaas-ui/issues

**Comment by jbakermd** [comment] 2017-04-11 17:07
Ok great. I'll create the issue on the ipaas-ui project when I've got it sorted.

**Comment by jbakermd** [comment] 2017-04-11 22:57
Ok I've narrowed this down to an issue with the screen updating. I see this manifesting in two places.

Place #1: On the loading screen, a status message displays a placeholder "Loading." message. This message is almost immediately changed under the covers to something like "Loading source/target documents.", which, in our test harness, automatically updates on the screen immediately - but it never updates within the iPAAS host component.

Place #2: When drawing lines. The lines are added to the line component at the appropriate time, but the component itself isn't redrawn within the iPAAS host component until a mouse move / mouse over event for a field fires off something that forces a redraw. Again, this issue doesn't show up in our test harness. 

@gashcrumb Do you have any idea why automatic redraw updates of the Data Mapper UI components wouldn't be firing?

**Comment by jbakermd** [comment] 2017-04-11 23:24
I've committed fixes in 3d1a73984e9556ab0d6a085da9c7d7ab7c83d0c9. These fixes get us past a few initialization issues that were blocking root causing this issue. Namely, the fixes for loading/saving stale mappings that refer to non-existent fields. I'm about to open an  issue on ipaas-ui for a small initialization change.

**Comment by jbakermd** [comment] 2017-04-11 23:32
Created the ipaas-ui issue related to the initialization change: https://github.com/redhat-ipaas/ipaas-ui/issues/415

**Comment by gashcrumb** [comment] 2017-04-12 12:11
I've a few views where I've had to inject ChagneDetectorRef from angular and manually trigger the change detector, this could be needed here.  As to why it's been necessary I'm not sure.  Here's an example:

pulling in the type -> https://github.com/redhat-ipaas/ipaas-ui/blob/master/src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts#L29

injecting -> https://github.com/redhat-ipaas/ipaas-ui/blob/master/src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts#L29

Usage -> https://github.com/redhat-ipaas/ipaas-ui/blob/master/src/app/integrations/edit-page/action-select/action-select.component.ts#L73-L77

As you can see from the TODO it was a surprise to me that this was needed :-)  But that being said, there's a few async calls in play here, and I'm wondering if there's a limit on how many nested `*ngIf`'s you can have, but haven't had a chance to investigate much further yet.

**Comment by jbakermd** [comment] 2017-04-12 15:57
Ah interesting. There's a similar hack I was surprised by. I forget the specific details, I *think* the issue was the view had already updated / drawn itself and I wasn't able to alter the model further. The commonly accepted answer to the problem is a ridiculous "setTimeout" call like so:

<pre>
// update the mapping line drawing after our fields have redrawn themselves
// without this, the x/y from the field dom elements is messed up / misaligned.
setTimeout(() => { 
  console.log("Redraw callback!");
  this.redrawLinesForMappings(); 
}, 1000);  
</pre>

from:

https://github.com/redhat-ipaas/datamapper-ui/blob/master/src/app/lib/ipaas-data-mapper/components/line.machine.component.ts#L181

:/

**Comment by gashcrumb** [comment] 2017-04-12 15:59
Yeah, it strikes me as the same stuff that was necessary in Angular 1, so maybe the change detection isn't all it's cracked up to be :-)

**Comment by gashcrumb** [comment] 2017-04-12 15:59
Maybe less time than 1 second might do the job, I usually keep it in the tens of milliseconds, basically just making it async to the current execution flow.

**Comment by jbakermd** [comment] 2017-04-12 16:00
It's strange though because it works in my very simple vanilla instance. I'm going to give your change detection fix a try.

**Comment by jbakermd** [comment] 2017-04-12 16:04
Yeah it was at 10 ms, the 1 second was an attempt to fix this issue - didn't :/ I'll put it back to 10.

**Comment by jbakermd** [comment] 2017-04-12 16:42
Thanks for that example, @gashcrumb. That fixed it. I'll change the initialization screen to use the same update method and have the fix in soon.

**Comment by gashcrumb** [comment] 2017-04-12 16:52
awesome, thanks!

**Comment by jbakermd** [comment] 2017-04-12 17:06
Fixed with 046380552b570f444aa085dd208f6326e8a51ed2. Thanks again, @gashcrumb.

**Closed by jbakermd** 2017-04-12 17:06 UTC

**Comment by gashcrumb** [comment] 2017-04-12 17:34
yep, that makes a huge difference, thanks!  @kcbabo this should roll into staging shortly...
